/* -*- Mode: java; -*- */

/**
 * HLModelUser.cls
 *
 * Copyright (c) 2018 HelpLightning Inc.
 * https://helplightning.com
 */

public class HLModelUser {
    /**
     * This is the model that represents
     *  a Help Lightning User object.
     */


    /**
     * Build a new model from a JSON
     *  response object
     */
    public static HLModelUser build(Object u) {
        return null;
    }



}
