/* -*- Mode: java; -*- */

/**
 * HLModelSearchUserTest.cls
 *
 * Copyright (c) 2017 HelpLightning Inc.
 * https://helplightning.com
 */

@isTest
public class HLModelSearchUserTest {

    private static String result1 = '[{"username":"p_1","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJHaGF6YWwiLCJleHAiOjE1Mjk4NTQyNjEsImlhdCI6MTUyNzI2MjI2MSwiaXNzIjoiR2hhemFsIiwianRpIjoiYWFjYzA2MWYtMTNlZS00YzE2LTkzMTAtOTg3OGZkYTI4M2IwIiwibmJmIjoxNTI3MjYyMjYwLCJwZW0iOnsidXNlciI6MTIyODh9LCJzdWIiOiJVc2VyOjEwNDUiLCJ0eXAiOiJhY2Nlc3MiLCJ2ZXIiOiIxMDAifQ.gvrXbGD2YWyncbtBQzhyskBvYwjFl2Nb4EGNR9eAMZ4","name":"Personal 1","id":1045,"avatar":{"thumb":null,"original":null},"active":true}]';
}
