#!/usr/bin/env bash
#
# Push everything in the metadata folder
#  to salesforce

# all of our lightning components
for i in metadata/aura/*
do
    echo "force aura push -f $i"
    force aura push -f $i
done

# all of our controllers
for i in metadata/classes/*.cls
do
    echo "force push -f $i"
    force push -f $i
done
