#!/usr/bin/env bash
#
# Set up a new scratch environment
#

## You must do an sf org login web -a ISV -d first and give
##  your DevHub enabled org an alias. Fill in
##  your alias for the HUBORG variable below.
HUBORG="ISV"

N=$1

if [ $# -ne 1 ]; then
    echo "Usage: $0 scratchName"
    exit 1
fi


echo "Creating new scratch org $N from $HUBORG..."

sf org create scratch -v ${HUBORG} -f config/project-scratch-def.json -y 30 -a $N && \
    sf project deploy start --target-org $N && \
    sf force user permset assign --target-org $N -n HelpLightning && \
    sf org open -r --target-org $N
